AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]  # VGG16 standard input size
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 16  
CLASSES: 2  
WEIGHTS: imagenet
LEARNING_RATE: 0.01  # Lower learning rate for better convergence

