# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ImageClassificationApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://imageclassificationapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2cba58f0aa7a4e59a0926c69692afdaf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0832a8990aa94a829e3b7c36b96cd9fd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: imageclassificationapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2cba58f0aa7a4e59a0926c69692afdaf }}/classification:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ImageClassificationApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f476c86654fd4ed390df9c80395a7c88 }}
        images: 'imageclassificationapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2cba58f0aa7a4e59a0926c69692afdaf }}/classification:${{ github.sha }}'